# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

install:
  - pip install -U -r requirements.txt
  - pip install -e .

# command to run tests, e.g. python setup.py test
script:
  - py.test --flake  --cov-report term --cov realdeal tests/

after_success:
  - coveralls
